crud group member api
sunh-1294/Training-php-and-vue pull request #45
Opened 2019-08-05 09:17 UTC by vinhtran-0912

## About

## TODO

N/A

## Related URLs

- Issue: https://link/to/issue

## UI changes

N/A

2019-08-05 13:41 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    protected $groupRepository;
/** var GroupRepository */

2019-08-05 13:41 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function __construct(GroupRepository $groupRepository)
Viết docs cho các function

2019-08-05 13:41 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $users = $group->users()->paginate(10);
giá trị thì đưa vào config

2019-08-05 13:41 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function create($group_id)
`$groupId`

2019-08-05 13:41 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function destroy(Group $group, Request $request, $user_id)
`$userId`

2019-08-06 01:53 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function store(Group $group, GroupUserRequest $request)
`@param` sai và thiếu ạ

2019-08-06 01:53 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function index(Group $group)
thiếu `param` ạ

2019-08-06 01:53 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function create(Group $group)
thiếu `@param` ạ

2019-08-06 01:54 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +    public function destroy(Group $group, Request $request, $userId)
Docs đang bị sai ạ

2019-08-06 01:54 UTC, sunh-1294 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $group->users()->create($request->all());
giải thích cho em đoạn logic code này với

2019-08-06 01:54 UTC, sunh-1294 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $groupUser = $group->groupUsers()->where('user_id', $userId)->firstOrFail();
Giải thích giúp em đoạn logic này với ạ

2019-08-06 02:20 UTC, vinhtran-0912 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $groupUser = $group->groupUsers()->where('user_id', $userId)->firstOrFail();
em tim kiếm thằng member của group theo user_id rồi sau đó e xóa nó đi ạ
vì thằng group có quan hệ với thằng groupUser nên em find nó theo userId thôi ạ

2019-08-06 02:26 UTC, vinhtran-0912 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $group->users()->create($request->all());
mình nhận request theo GroupUserRequest validate lun bên kia nên mình nhận request->all luôn ạ

2019-08-06 09:41 UTC, leductienttkt commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $groupUser = $group->groupUsers()->where('user_id', $userId)->firstOrFail();
$groupUser = $group->groupUsers()->findOrFail($userId) đc ko em

2019-08-06 09:47 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param App\Models\Group $group;
vì bên trên đã use rồi thì chỗ này chỉ cần Group thôi ạ
`@param Group $group;`

2019-08-06 09:47 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param App\Models\Group $group;
`@param App\Models\Group $group;`

2019-08-06 09:47 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Models\Group $group;
`@param App\Models\Group $group;`

2019-08-06 09:47 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Http\Requests\GroupUserRequest $request;
`@param App\Models\GroupUserRequest $request;`

2019-08-06 09:47 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Models\Group $group;
request

2019-08-07 02:57 UTC, vinhtran-0912 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Http\Requests\GroupUserRequest $request;
ủa request vì sao lại nằm trong model a

2019-08-07 02:58 UTC, tanpv-2025 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  GroupRepository  $groupRepository
Cái này thiếu 1 param này

2019-08-07 03:00 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Http\Requests\GroupUserRequest $request;
b ý nhầm anh ạ

2019-08-07 03:02 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @return \Illuminate\Http\Response
ở dưới return view mà ở Docs anh lại return `\Illuminate\Http\Response` ạ

2019-08-07 03:02 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @return \Illuminate\Http\Response
ở dưới return view mà ở Docs anh lại return `\Illuminate\Http\Response` ạ ?

2019-08-07 03:02 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @return \Illuminate\Http\Response
sai Docs ak

2019-08-07 03:03 UTC, quanttn-2024 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $data = $request->all([
$request->all() thì nó lấy hết rồi mà đâu cần bỏ thêm user_id vô nữa cậu. Hay là $request->only vậy?

2019-08-07 03:03 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        ]);
```suggestion
        $data = $request->all(['user_id']);
```

2019-08-07 03:03 UTC, quynt-1571 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @param  App\Http\Requests\GroupUserRequest $request;
a nhầm :v

2019-08-07 03:04 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +     * @return \Illuminate\Http\Response
Sai Docs phần `returrn` ạ

2019-08-07 03:04 UTC, vietnc-1636 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        // $groupUser = $group->groupUsers()->find($userId);
không dùng thì xóa đi ạ

2019-08-07 03:04 UTC, quanttn-2024 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        // $groupUser = $group->groupUsers()->find($userId);
không dùng thì xóa dòng này đi nè

2019-08-07 03:05 UTC, tanpv-2025 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        $group->groupUsers()->attach($group->id,$data);
```diff
-($group->id,$data)
+($group->id, $data)
```

2019-08-07 03:29 UTC, sunh-2087 approved these changes

2019-08-07 03:30 UTC, quanttn-2024 commented on nano.save
> +m
file này là file gì vậy cậu?

2019-08-07 03:33 UTC, vinhtran-0912 commented on nano.save
> +m
kẹp phím tạo nhầm :3

2019-08-07 03:36 UTC, quanttn-2024 approved these changes

2019-08-07 03:40 UTC, vietnc-1636 approved these changes

2019-08-07 04:01 UTC, quynt-1571 approved these changes

2019-08-07 07:41 UTC, vuongvt1905 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        if($result){
```diff
- if($result){
+ if ($result) {
```

2019-08-07 07:42 UTC, vuongvt1905 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +        else{
```diff
- else{
+ else {
```

2019-08-07 07:48 UTC, vuongvt1905 requested changes

2019-08-07 07:48 UTC, vuongvt1905 commented on resources/views/admin/group/members/form.blade.php
> +
dư dòng trống

2019-08-07 07:48 UTC, vuongvt1905 commented on resources/views/admin/group/members/form.blade.php
> +                <datalist id="suggestionList">
indent

2019-08-07 07:48 UTC, vuongvt1905 commented on resources/views/admin/group/members/index.blade.php
> +
dư dòng trống

2019-08-07 07:48 UTC, vuongvt1905 commented on resources/views/admin/groups/index.blade.php
> +                        <td> --}}
không dùng thì xóa đi

2019-08-07 07:48 UTC, vuongvt1905 commented on resources/views/admin/group/members/index.blade.php
> +    <div class="">
```diff
- <div class="">
+ <div>
```

2019-08-07 07:48 UTC, vuongvt1905 commented on app/Http/Controllers/Admin/Group/GroupMemberController.php
> +
dư dòng trống

2019-08-07 07:48 UTC, leductienttkt commented on resources/sass/group.scss
> +.action-group a{
indent nì
 viết cái a {...} vào trong luôn

2019-08-07 07:48 UTC, leductienttkt commented on resources/views/admin/group/members/form.blade.php
> +
thừa dòng

2019-08-07 07:50 UTC, vuongvt1905 requested changes

2019-08-07 07:50 UTC, vuongvt1905 commented on resources/views/admin/group/members/form.blade.php
> +                        @endforeach
indent đang sai

2019-08-07 08:17 UTC, leductienttkt commented on resources/views/admin/group/members/form.blade.php
> +        <input type="hidden" name="user_id" id="email-hidden"/>
thiếu cái </div> nè

2019-08-07 08:19 UTC, leductienttkt approved these changes

2019-08-07 08:19 UTC, merged